version: "3.9"
services:
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/dbo"
      SPRING_FLYWAY_URL: "jdbc:postgresql://postgres:5432/dbo"
      SPRING_REDIS_HOST: "redis"
    ports:
      - "8080:8080"
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: "dbo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  data:
  redis-data: