spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/dbo
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/dbo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  redis:
    host: localhost
    port: 6379
#    hibernate:
#      ddl-auto: validate
  task:
    scheduling:
      pool:
        size: 10
  cache:
    jcache:
      config: classpath:/ehcache.xml

logging:
  level:
    org.springframework.cache: TRACE
#    root: debug

app:
  deposit:
    scheduler:
      interval: 30000
